### ISSUE TITLE
Pod has some problems.

### ISSUE THREAD

**Issue by lou-lan** [antrix1989/ANLongTapButton#3]
Pod has some problems.

Code is not the same.

**Comment by antrix1989** [comment]
@lou-lan can you provide more details?

**Comment by lou-lan** [comment]
Cocoapods code and GitHub code is not the same, pod will be reported to the wrong, I downloaded GitHub manually drag it will not be reported to the wrong, I think it is your cocoapods does not update. Sorry my English is not good。

**Comment by AnasMostefaoui** [comment]
The pod version is still on 1.2.0, this is why you get issues.
you can get the last update using the following : 
pod 'ANLongTapButton',:git => 'https://github.com/antrix1989/ANLongTapButton.git'

**Comment by lou-lan** [comment]
The Swift 3 implementation is the actively maintained version on the master branch.
I know, Thank you very much.
